name: Build and test

on: [push, pull_request]

jobs:
  tests:
    name: Build and test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - gz-version: "garden"
            ros-distro: "humble"
    container:
      image: ubuntu:20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: .github/workflows/build-and-test.sh
        env:
          IGNITION_VERSION: ${{ matrix.gz-version  }}
          ROS_DISTRO: ${{ matrix.ros-distro }}